export const refs = {
  input: document.querySelector('[data-input-search]'),
  watched: document.querySelector('[data-watched]'),
  queue: document.querySelector('[data-queue]'),
  students: document.querySelector('[data-students-open]'),
  backdrop: document.querySelector('[data-card-modal]'),
  closeModal: document.querySelector('[data-modal-close]'),
  openModal: document.querySelector('[data-modal-open]'),
  openVideo: document.querySelector('[data-video-open]'),
  openTrailer: document.querySelector('[data-trailer]'),
  videoModal: document.querySelector('[data-video-modal]'),
  trailerWrap: document.querySelector('.trailer__inner'),
  closeVideo: document.querySelector('[data-video-close]'),
  modal: document.querySelector('.backdrop__card'),
  addWatched: document.querySelector('[data-watched-btn]'),
  addQueue: document.querySelector('[data-queue-btn]'),
};
